language: node_js
node_js:
- '8.0'
deploy:
  provider: heroku
  api_key:
    secure: vmj3GEi+vg/I4XyHIuUig/uXcfjZqU9WwxipRsslYYpA4MoqYtunbh0MsBdyctCCYkxQkdzhNk3lP5lyZHADXrI8n6/DdUqdW6dfpLQEiekHJ6RV87OJTqBgpK2nlIYS4m3nF+A0rOmSfrTLiEK1M+Nm3L7LRm8Tys+vY3zCYnp91KANYvwnHLE5nZCoTxdZjLY+BW7J4GRVpAuECIzp2vSg+ZqZwSvogQf0B0b3Yvtvam4Su3SISFhteYynfzlxvtD8aqs6l33+jfkA4kOQmPuhQleUpH/nZ+km8OHrVFbOQpmaOwje9yB9PDXv7eeznibwOv0/b4MwQTgiiCaPk1atuoooBxN5Wp0GL+ynUAqXLSNBDP0tnZx38cERIOgii9QkulY3qiA3Y1iNb4yCUtnKbkcYWaDBe1OG/Vil/R6qugVcctPKWbhYgIb/WwOvsjusm4ANeYvMa6arMQqL4JisFDXTYwhda+9YBC7ckG8t4D3jTZu4ApwODgXbuehfduerXKUts2fheohFXx1JXCkGK6F62+ufQ1prG0l+KGSbZxUktZBBkIIHjQGdfT/lauGDVPbY5MgjcKlxxHRAIx7dxYnq6Jq+H2XrgfMNKWlmZkqnegkA0mRtdZHpxAKionJjkWy9Y7L7ovXKinSyPsDQSn4botX5MpGG+UkQH9A=
