version: '3'

services:

  test:
    build:
      context: .
    image: registry.heroku.com/infinite-hamlet-32574/web:latest
    command: # npm test
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
