version: '3'

services:

  web:
    build: .
    image: registry.heroku.com/simple-frontend/web:latest
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app/:rw
    environment:
    - NODE_ENV=dev
